#!/usr/bin/env python3
"""
Encode a CloudModel JSON fallback as a gzip-compressed, XOR-obfuscated
Rust source file consumable by the obfuscated_cloud_model_fallback! macro
in flodbadd::cloud_model_fallback.

Why: the previous shape (`pub static FOO_DB: &str = r#"..."#;`) embeds the
JSON as a single contiguous UTF-8 block in the binary's rodata section.
strings(1) and Microsoft Defender's Stealc/Stealga ML model both read it
trivially, and our JSON corpora (sensitive_paths_db.rs, etc.) look like
classic credential-stealer reconnaissance to the model. Compressing
destroys the readable substrings, XOR breaks magic-byte signature scanners,
and `Lazy<String>` decodes once on first access at runtime.

Usage:
    python3 tools/encode_cloud_fallback.py <input.json> <output.rs> <STATIC_NAME> [comment]

Example:
    python3 tools/encode_cloud_fallback.py \
        ../threatmodels/lanscan-sensitive-paths-db.json \
        src/sensitive_paths_db.rs \
        SENSITIVE_PATHS_DB \
        "Built in default sensitive paths db"

Re-run from update-threats.sh after each `threatmodels` fetch. The output
is a small Rust file; the bulky JSON is now an obfuscated byte array that
is only decoded on demand at runtime.
"""

from __future__ import annotations

import gzip
import sys
from pathlib import Path

# Must match XOR_KEY in flodbadd/src/cloud_model_fallback.rs.
XOR_KEY = 0xA7

# 16 bytes per line keeps the generated Rust file readable in diffs without
# producing absurdly long lines for the 75 MB vendor_vulns_db.
BYTES_PER_LINE = 16


def encode(plain_json: bytes) -> bytes:
    """gzip-compress then XOR-encode."""
    compressed = gzip.compress(plain_json, compresslevel=9, mtime=0)
    return bytes(b ^ XOR_KEY for b in compressed)


def format_rust(name: str, comment: str, plain_len: int, obfuscated: bytes) -> str:
    """Render the encoded bytes as a Rust file using
    `obfuscated_cloud_model_fallback!`.

    The comment block records the original size + compression ratio so
    reviewers can sanity-check the artifact without decoding it.
    """
    ratio = plain_len / max(1, len(obfuscated))
    header = f"""// {comment}
//
// Generated by tools/encode_cloud_fallback.py from the upstream
// threatmodels JSON. The bytes below are gzip-compressed (level 9) and
// XOR-encoded with key 0x{XOR_KEY:02X} so the readable JSON content does
// NOT appear as a literal string in the compiled binary. See
// `src/cloud_model_fallback.rs` for the why and the runtime decoder.
//
// Encoded size: {len(obfuscated)} bytes (plain: {plain_len}, ratio: {ratio:.2f}x).
//
// DO NOT EDIT BY HAND. Re-run the encoder if the upstream JSON changes.

use crate::obfuscated_cloud_model_fallback;

obfuscated_cloud_model_fallback!(pub {name}: &[
"""
    body_lines: list[str] = []
    for chunk_start in range(0, len(obfuscated), BYTES_PER_LINE):
        chunk = obfuscated[chunk_start : chunk_start + BYTES_PER_LINE]
        hex_bytes = ", ".join(f"0x{b:02x}" for b in chunk)
        body_lines.append(f"    {hex_bytes},")
    body = "\n".join(body_lines)
    footer = "\n]);\n"
    return header + body + footer


def main(argv: list[str]) -> int:
    if len(argv) < 4:
        print(__doc__, file=sys.stderr)
        return 2
    input_path = Path(argv[1])
    output_path = Path(argv[2])
    name = argv[3]
    comment = argv[4] if len(argv) >= 5 else f"Built in default {name} db"

    plain = input_path.read_bytes()
    obfuscated = encode(plain)
    rendered = format_rust(name, comment, len(plain), obfuscated)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(rendered)
    print(
        f"  encoded {input_path.name}: plain {len(plain):,} -> "
        f"obfuscated {len(obfuscated):,} bytes "
        f"({len(plain) / max(1, len(obfuscated)):.2f}x compression) -> {output_path}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
