// Built in default port vulns db (obfuscated)
//
// Generated by tools/encode_cloud_fallback.py from the upstream
// threatmodels JSON. The bytes in `port_vulns_db.bin` are gzip-compressed
// (level 9) and XOR-encoded with key 0xA7 so the readable
// JSON content does NOT appear as a literal string in the compiled
// binary. See `src/cloud_model_fallback.rs` for the why and the runtime
// decoder.
//
// Encoded size: 138036 bytes (plain: 1266385, ratio: 9.17x).
//
// DO NOT EDIT BY HAND. Re-run the encoder if the upstream JSON changes.

use crate::obfuscated_cloud_model_fallback;

obfuscated_cloud_model_fallback!(pub PORT_VULNS: include_bytes!("port_vulns_db.bin"));
