// Built in default device profiles db (obfuscated)
//
// Generated by tools/encode_cloud_fallback.py from the upstream
// threatmodels JSON. The bytes in `profiles_db.bin` are gzip-compressed
// (level 9) and XOR-encoded with key 0xA7 so the readable
// JSON content does NOT appear as a literal string in the compiled
// binary. See `src/cloud_model_fallback.rs` for the why and the runtime
// decoder.
//
// Encoded size: 1351 bytes (plain: 15092, ratio: 11.17x).
//
// DO NOT EDIT BY HAND. Re-run the encoder if the upstream JSON changes.

use crate::obfuscated_cloud_model_fallback;

obfuscated_cloud_model_fallback!(pub DEVICE_PROFILES: include_bytes!("profiles_db.bin"));
