// Built in default whitelists db (obfuscated)
//
// Generated by tools/encode_cloud_fallback.py from the upstream
// threatmodels JSON. The bytes in `whitelists_db.bin` are gzip-compressed
// (level 9) and XOR-encoded with key 0xA7 so the readable
// JSON content does NOT appear as a literal string in the compiled
// binary. See `src/cloud_model_fallback.rs` for the why and the runtime
// decoder.
//
// Encoded size: 1876 bytes (plain: 13320, ratio: 7.10x).
//
// DO NOT EDIT BY HAND. Re-run the encoder if the upstream JSON changes.

use crate::obfuscated_cloud_model_fallback;

obfuscated_cloud_model_fallback!(pub WHITELISTS: include_bytes!("whitelists_db.bin"));
